apiVersion: v1
kind: Pod
metadata:
  name: gallery
spec:
  containers:
    - name: gallery
      image:  rsdemos.azurecr.io/picture-gallery:1.0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 80