apiVersion: v1
kind: Service
metadata:
  name: gallery-svc
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  selector:
    app: gallery
  ports:
  - port: 8080      # The port on which the service listens
    targetPort: 80  # The target port that is exposed by your POD(s)