apiVersion: v1
kind: Service
metadata:
  name: gallery-svc-blue
spec:
  type: LoadBalancer
  selector:
    app: gallery
    version: v1
  ports:
  - port: 8080      # The port on which the service listens
    targetPort: 80  # The target port that is exposed by your POD(s)
---
apiVersion: v1
kind: Service
metadata:
  name: gallery-svc-green
spec:
  type: LoadBalancer
  selector:
    app: gallery
    version: v2
  ports:
  - port: 8090      # The port on which the service listens
    targetPort: 80  # The target port that is exposed by your POD(s)