apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: {{ .Values.backend.internalPort }}
    targetPort: 8000