apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-files
data:
  config.json: |-
    {
      "someKey": "someValue",
      "answerToEverything": 42,
      "bestCharacter": {
        "name": "Arthur Dent",
        "species": "Human"
      }
    }