apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gallery
      version: v4
  template:
    metadata:
      labels:
        app: gallery
        version: v4
    spec:
      containers:
      - name: gallery
        image: rsdemos.azurecr.io/picture-gallery:2.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 2
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gallery-svc
spec:
  type: LoadBalancer
  selector:
    app: gallery
    version: v4
  ports:
  - port: 8080
    targetPort: 80
